### ISSUE TITLE
怎么修改配置文件？

### ISSUE THREAD

**Issue by ustcjerry** [akaxincom/openzaly#7]
比如修改监听端口？

**Comment by SAM2O2O** [comment]
默认启动的时候会默认端口，如果需要需要修改端口
1.脚本启动 sh start.sh {新的端口}  比如 sh start.sh 2022 启动就是使用2022端口
2.java -jar -Dsite.port=2022 openzaly-server.jar 这样也可以修改端口
3.java -jar openzaly-server.jar  -h 可以看到支持的参数

**Comment by sisishiliu** [comment]
-h 参数的jar包今天晚些时候回同步出来。
也可以现在直接从源码编译。
